#pragma once

#define NOMINMAX

#include <string>
#include <vector>
#include <memory>
#include <iostream>
#include <stdexcept>
#include <cstdlib>
#include <filesystem>
#include <algorithm>
#include <charconv>
#include <regex>
#include <sstream>
#include <cctype>
#include <cmath>
#include <set>
#include <map>
#include <iomanip>
#include <fstream>
#include <utility>
#include <type_traits>
#include <unordered_map>
#include <unordered_set>

#include "core/domain/entities/Actor.h"
#include "core/domain/entities/Analysis.h"
#include "core/domain/entities/Annual.h"
#include "core/application/workspace/AppState.h"
#include "core/domain/entities/Contract.h"
#include "core/application/storage/DeletionImpact.h"
#include "core/application/import/ImportLog.h"
#include "core/application/export/ExportLog.h"
#include "core/application/import/draft/StatementDraft.h"
#include "core/application/import/draft/TransactionDraft.h"
#include "core/domain/entities/Property.h"
#include "core/domain/entities/Statement.h"
#include "core/domain/entities/Transaction.h"
#include "core/application/analysis/RunAnalysisResult.h"
#include "core/application/workspace/AppState.h"
#include "core/application/workspace/DeletionImpact.h"
#include "core/application/import/ImportLog.h"
#include "core/application/export/ExportLog.h"
#include "core/application/import/draft/StatementDraft.h"
#include "core/application/import/draft/TransactionDraft.h"

using core::domain::Actor;
using core::domain::Analysis;
using core::domain::Annual;
using core::domain::AppState;
using core::domain::Contract;
using core::domain::DeletionImpact;
using core::domain::Property;
using core::domain::Statement;
using core::domain::Transaction;
using core::domain::AnalysisResult;
using core::domain::AnalysisTransaction;
using core::domain::ImportLog;
using core::domain::ExportLog;
using core::domain::StatementDraft;
using core::domain::TransactionDraft;
