#define AppExeName "fossredder.exe"
#define AppDisplayName "FOSSredder"

#include "includes\setup.iss"
#include "includes\languages.iss"
#include "includes\messages.iss"
#include "includes\tasks.iss"
#include "includes\files.iss"
#include "includes\icons.iss"
#include "includes\run.iss"
#include "includes\maintenance.iss"
