/**
 * @file ui/qml/FossRedder/Theme/DarkPalette.qml
 * @brief Provides dark mode theme colors.
 */

pragma ComponentBehavior: Bound

import QtQuick 2.15

QtObject {
    readonly property color primary: "#6BB6FF"
    readonly property color accent: "#4DD4FF"
    readonly property color background: "#101820"
    readonly property color surface: "#17222B"
    readonly property color surfaceAlt: "#202D36"
    readonly property color border: "#3A4D5A"
    readonly property color textPrimary: "#EEF6FA"
    readonly property color textMuted: "#A9BCC6"
    readonly property color danger: "#FF8A80"
    readonly property color success: "#81C784"
    readonly property color warning: "#FFB74D"
    readonly property color successStrong: "#A5D6A7"
    readonly property color borderSoft: "#32434F"
    readonly property color borderLight: "#2A3944"
    readonly property color borderMedium: "#435765"
    readonly property color borderStrong: "#5A7180"
    readonly property color statusBarBackground: "#14202A"
    readonly property color statusBarBorder: "#263947"
    readonly property color placeholderText: "#9AAEB8"
    readonly property color selectionHighlight: "#3A5D76"
    readonly property color selectionBorder: "#6BA5C8"
    readonly property color sidebarHoverFill: "#20313D"
    readonly property color sidebarHoverBorder: "#4A6270"
    readonly property color toolbarBackgroundTop: "#182D3A"
    readonly property color toolbarBackgroundBottom: "#122431"
    readonly property color toolbarItemText: "#A9BCC6"
    readonly property color toolbarItemActiveText: "#EEF8FC"
    readonly property color toolbarItemHoverFill: "#1B303C"
    readonly property color toolbarItemSelectedFill: "#25495D"
    readonly property color toolbarItemSelectedBorder: "#5E91AC"
    readonly property color toolbarGroupActiveText: "#C8E2EC"
    readonly property color appMenuBackgroundTop: "#182B37"
    readonly property color appMenuBackgroundBottom: "#13232E"
    readonly property color appMenuText: "#EEF6FA"
    readonly property real panelShadowOpacity: 0.11
    readonly property color statusSuccessFill: "#20372D"
    readonly property color statusSuccessText: "#BFE4CC"
    readonly property color statusSuccessBorder: "#426753"
    readonly property color statusWarningFill: "#3B3324"
    readonly property color statusWarningText: "#F0CF8B"
    readonly property color statusWarningBorder: "#6B5632"
    readonly property color statusDangerFill: "#3A2A2C"
    readonly property color statusDangerText: "#E7B9B4"
    readonly property color statusDangerBorder: "#654346"
    readonly property color statusInfoFill: "#233849"
    readonly property color statusInfoText: "#B8DCF0"
    readonly property color statusInfoBorder: "#486B80"
    readonly property color statusNeutralFill: "#202D36"
    readonly property color statusNeutralText: "#A9BCC6"
    readonly property color statusNeutralBorder: "#3A4D5A"
    readonly property color toolbarBorder: "#2C4A5F"
    readonly property color divider: "#36586E"
    readonly property color shadow: "#000000"
    readonly property color subtlePrimaryFill: "#1E405C"
    readonly property color primaryText: "#07131D"
    readonly property color buttonFill: "#21313D"
    readonly property color buttonText: "#E7F2F7"
    readonly property color buttonMutedText: "#C5D6DF"
    readonly property color buttonConfirmFill: "#264A61"
    readonly property color buttonConfirmText: "#EEF8FC"
    readonly property color buttonConfirmBorder: "#4F7F99"
    readonly property color controlFill: "#182631"
    readonly property color controlHoverFill: "#20313D"
    readonly property color controlFocusBorder: "#6BA5C8"
    readonly property color controlHoverBorder: "#4A6270"
    readonly property real controlShadowOpacity: 0.18
    readonly property real popupShadowOpacity: 0.32
    readonly property color checkboxFill: "#17222B"
    readonly property color checkboxHoverFill: "#20313D"
    readonly property color checkboxCheckedFill: "#6BA5C8"
    readonly property color checkboxBorder: "#5A7180"
    readonly property color checkboxCheck: "#07131D"
    readonly property color scrollBarThumb: "#3D5F72"
    readonly property color scrollBarThumbHover: "#4F7F99"
    readonly property color menuFill: "#17222B"
    readonly property color menuHoverFill: "#1E405C"
    readonly property color appMenuPopupFill: "#182631"
    readonly property color appMenuPopupBorder: "#3D5564"
    readonly property color appMenuPopupText: "#EAF4F8"
    readonly property color appMenuPopupMutedText: "#9DB2BD"
    readonly property color appMenuPopupHoverFill: "#223846"
    readonly property color appMenuSeparator: "#334A59"
}
