/**
 * @file ui/qml/FossRedder/Theme/LightPalette.qml
 * @brief Provides light mode theme colors.
 */

pragma ComponentBehavior: Bound

import QtQuick 2.15

QtObject {
    readonly property color primary: "#3E6F8F"
    readonly property color accent: "#5AA8A5"
    readonly property color background: "#EEF3F5"
    readonly property color surface: "#FBFCFD"
    readonly property color surfaceAlt: "#F4F8FA"
    readonly property color border: "#D3DEE4"
    readonly property color textPrimary: "#22313A"
    readonly property color textMuted: "#657781"
    readonly property color danger: "#B45A54"
    readonly property color success: "#2F8061"
    readonly property color warning: "#A36F22"
    readonly property color successStrong: "#3B8E6C"
    readonly property color borderSoft: "#E0E8EC"
    readonly property color borderLight: "#EAF0F3"
    readonly property color borderMedium: "#CAD8DF"
    readonly property color borderStrong: "#AFC2CD"
    readonly property color statusBarBackground: "#E8F0F4"
    readonly property color statusBarBorder: "#D3E1E8"
    readonly property color placeholderText: "#87949B"
    readonly property color selectionHighlight: "#D7E8F3"
    readonly property color selectionBorder: "#6EA1BF"
    readonly property color sidebarHoverFill: "#F6FAFB"
    readonly property color sidebarHoverBorder: "#B8CCD6"
    readonly property color toolbarBackgroundTop: "#F3F8FA"
    readonly property color toolbarBackgroundBottom: "#E4EEF3"
    readonly property color toolbarItemText: "#536872"
    readonly property color toolbarItemActiveText: "#1F3F52"
    readonly property color toolbarItemHoverFill: "#F7FBFC"
    readonly property color toolbarItemSelectedFill: "#D7EAF2"
    readonly property color toolbarItemSelectedBorder: "#8EB5C8"
    readonly property color toolbarGroupActiveText: "#3C728C"
    readonly property color appMenuBackgroundTop: "#F7FAFB"
    readonly property color appMenuBackgroundBottom: "#EAF2F5"
    readonly property color appMenuText: "#2D3D46"
    readonly property real panelShadowOpacity: 0.025
    readonly property color statusSuccessFill: "#EAF4EE"
    readonly property color statusSuccessText: "#2F8061"
    readonly property color statusSuccessBorder: "#BCD9C8"
    readonly property color statusWarningFill: "#F7F0E2"
    readonly property color statusWarningText: "#8C6425"
    readonly property color statusWarningBorder: "#DEC994"
    readonly property color statusDangerFill: "#F6ECEA"
    readonly property color statusDangerText: "#9A4A45"
    readonly property color statusDangerBorder: "#D8BDB8"
    readonly property color statusInfoFill: "#E8F1F6"
    readonly property color statusInfoText: "#416F89"
    readonly property color statusInfoBorder: "#BCD0DA"
    readonly property color statusNeutralFill: "#F4F8FA"
    readonly property color statusNeutralText: "#657781"
    readonly property color statusNeutralBorder: "#D3DEE4"
    readonly property color toolbarBorder: "#D2E1E8"
    readonly property color divider: "#B9CDD8"
    readonly property color shadow: "#000000"
    readonly property color subtlePrimaryFill: "#DDECF3"
    readonly property color primaryText: "#FFFFFF"
    readonly property color buttonFill: "#F8FBFC"
    readonly property color buttonText: "#243645"
    readonly property color buttonMutedText: "#586B75"
    readonly property color buttonConfirmFill: "#D9E9F0"
    readonly property color buttonConfirmText: "#213F52"
    readonly property color buttonConfirmBorder: "#AEC9D6"
    readonly property color controlFill: "#FBFCFD"
    readonly property color controlHoverFill: "#F6FAFB"
    readonly property color controlFocusBorder: "#6EA1BF"
    readonly property color controlHoverBorder: "#B8CCD6"
    readonly property real controlShadowOpacity: 0.055
    readonly property real popupShadowOpacity: 0.11
    readonly property color checkboxFill: "#F8FBFC"
    readonly property color checkboxHoverFill: "#EEF6F8"
    readonly property color checkboxCheckedFill: "#3E6F8F"
    readonly property color checkboxBorder: "#AFC2CD"
    readonly property color checkboxCheck: "#FFFFFF"
    readonly property color scrollBarThumb: "#C4D6DE"
    readonly property color scrollBarThumbHover: "#AEC9D6"
    readonly property color menuFill: "#FBFCFD"
    readonly property color menuHoverFill: "#DDECF3"
    readonly property color appMenuPopupFill: "#FBFCFD"
    readonly property color appMenuPopupBorder: "#C9D9E1"
    readonly property color appMenuPopupText: "#263843"
    readonly property color appMenuPopupMutedText: "#697B85"
    readonly property color appMenuPopupHoverFill: "#E4F0F5"
    readonly property color appMenuSeparator: "#D8E4EA"
}
